### ISSUE TITLE
Display style

### ISSUE THREAD

**Issue by psychemedia** [lgpage/nbtutor#37]
The colour theme in the animation offers low contrast displays when stepping through the trace. Is there an easy way of setting background and font colours, or selecting a high contrast  / websafe / colourblind safe palette?

**Comment by lgpage** [comment]
With #44 it is possible to update color variables either by adding custom css to the Jupyter folder (see https://stackoverflow.com/a/52816576) or by using the `%%html` magic. The variables are

```css
%%html
<style>
:root {
  --nbt-canvas-background: #f7f7f7;
  --nbt-object-background: #ffffff;

  --nbt-frame-text: #000000;
  --nbt-frame-background: #ffffff;
  --nbt-frame-active-text: pink;
  --nbt-frame-active-background: #4682b4;

  --nbt-connector: #005566;
  --nbt-hover-text: #ffffff;
  --nbt-hover-background: #6610f2;

  --nbt-gutter-previous: #0000ff;
  --nbt-gutter-current: #008000;
  --nbt-gutter-next: #6610f2
}
</style>
```
